### ISSUE TITLE
Moon/Sun/Stars.. are still visible.

### ISSUE THREAD

**Issue by verymilan** [minetest-mods/skybox#5]
...and mess up the skyboxes :(
![screenshot_20210126_210947](https://user-images.githubusercontent.com/10698140/105899409-ea39ba00-601a-11eb-91e8-6cdab77f693b.png)

Tested with core 5.3.0 and newer

**Comment by LoneWolfHT** [comment]
![image](https://user-images.githubusercontent.com/28972859/108111667-dbf32280-7049-11eb-8280-ca81a06726a5.png)

Near-latest 5.4
